[package]
name = "aura"
version = "0.1.0"
edition = "2024"

[dependencies]
ntex = { version = "2.17.0", features = ["tokio"] }
reqwest = { version = "0.12.25", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
